Code-the-Dream-School/MyKitchenApp-front

package-lock.json
package.json
src/App.js
src/Pages/LogOut/LogOut.js
src/components/Layout/LayoutPrivate.js
src/components/Layout/LayoutPublic.js
src/components/Navbar/Navbar.js
src/components/Navbar/ResponsiveAppBar.js
src/index.js

Responsive functional navbar. Layouts and routes implemented for the app.
https://mui.com/material-ui/getting-started/installation/
npm install @mui/icons-material
https://reactrouter.com/en/v6.3.0/getting-started/installation#basic-installation
npm install react-router-dom@6
closes #27 
closes #31 
closes #51 
The functional navbar is created, and each button leads to the corresponding page.
Public and Private Layouts created
Public layout for the landing page, sign/signup page, and logout.
Private Layout with Navbar for all the rest pages.
React router installed. Routes configured.
|    | :100: Add tests …

Nav bar private pages dev

---

package-lock.json
package.json
src/components/Footer/FooterPrivate.js

A public footer created for all pages except Landing, Sign in and Sign up pages.
https://mui.com/material-ui/
closes #37
This contains name of the application, copyright sign, year and a link to the application repo on GitHub

Footer private footer dev

---

src/components/Footer/FooterPublic.js

A public footer was created for Landing, Sign in and Sign up pages.
https://mui.com/material-ui/
Closes #42 
This contains name of the application, copyright sign and year

a public footer for landing, sign in and sign up pages

---

src/Pages/SignIn/SignIn.js

send a post request to server endpoint "/login"
store the token in the local storage of the browser
if successful, redirect to dashboard
https://www.makeuseof.com/redirect-user-after-login-react/
how to redirect user using react router
closes #60 
When Login is successful direct the user to the dashboard and save the current user data in the global context
If unsuccessful show the error message on the same page

connect login page to server

---

package-lock.json
package.json
src/App.js
src/Pages/Dashboard/Dashboard.js
src/Pages/Search/Search.js
src/Pages/Search/SearchForm.js
src/Pages/Search/SearchResult.js

A layout of Search Form was added, react icons were installed
[https:// www.mui.com](https://mui.com/material-ui/api/dialog/)
Closes #48 
add a title
add an input for ingredients
add a checkbox for intolerance options
add a search button
add a cancel button

Layout search form dev

---

src/App.css
src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js

Validation for signin page
- empty email or empty password will cause error
- wrong password will cause errors
Validation for signup pages
- empty name,email or password will cause error
- confirm password not matching will cause error
- wrong email format will cause error
closes #84 
show error if wrong credentials are entered on sign in page
show error if wrong information provided on sign up page
signin page test
1. open signin page
2. try clicking signin button with empty fields
3. try with wrong …

add validation to signup and signin pages

---

src/App.js
src/Pages/Landing/Landing.js
src/Pages/LogOut/LogOut.js
src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js

Fix the hover status on get started button
Redirect to log in on click
Remove log out pages
Make axios call async
closes #86 
on hover button is still visible 
on click sign in page appears
|     ✓ | :bug: Bug fix              |
| | :sparkles: New feature     |

adjust hover on get started button

---

src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js

Add front-end validation for sign-in and signup pages
Change token name
https://mui.com/material-ui/react-text-field/#validation
closes #90 
-The email field should be validated in the front end before clicking the Create Account button.
-Password field should be validated in the front end
-disable the Create Account button until the user has filled all the fields
|    ✓| :bug: Bug fix              |
|    ✓| :hammer: Refactoring       |
- Try entering an invalid email
- Try typing Password until 8 characters
- Try typing 2 different password for sign up

add frontend validation, update token name

---

src/App.css
src/App.js
src/Pages/Landing/Landing.js
src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js

Add sign-in and sign up page to landing
Remove sign in and sign up routes
Closes #89 
-Move the signin page data into landing page and delete the signin route
|     ✓ | :bug: Bug fix              |
Go to localhost:3000
Try click sign up link at the button
Try click sign in link at the button
Try sign in and sign up

move signin and signup pages to landing page

---

package-lock.json
package.json
src/Pages/Dashboard/Dashboard.css
src/Pages/Dashboard/Dashboard.js
src/components/ReusableCard/ReusableCard.js

The dashboard contains 3 categories of choice, Breakfast, Salad, and Drink. 
Recipes now are random.  
Recipes have carousels.
https://splidejs.com/integration/react-splide/
closes #55 
AC:
Dashboard displaying random recipes.
|   ✓  | :bug: Bug fix              |
|  | :sparkles: New feature     |

Reusable card dashboard dev

---

src/Pages/Search/SearchResult.js

Just basic layout of the Search Result page. Requesting to pull these changes because I need to add functionality to this page. Reusable cards does not show anything because this functionality will be added in a functionality branch of Search result page.
[www.mui.com](https://mui.com/material-ui/getting-started/overview/)
links #49 
Page has a title, filter buttons, cards with recipes.
Each card should have title, picture and a heart icon.

Layout search result dev

---

src/App.js
src/Pages/Landing/Landing.js
src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js
src/components/Layout/LayoutPrivate.js

Redirect private routes if the user logged in.
Remove the state for the token.
Private routing in react -https://www.robinwieruch.de/react-router-private-routes/
Closes #94 
Protect all the private pages so only the authenticated users can access the routes
|   ✓  | :hammer: Refactoring       |
- Make sure there is no token in local storage.
- Go to the home page and type /dashboard on the Url
- It should take you sign in page.
- Try sign in if you have an account if not use sign up page to sign in.
- After sign in ,you should go to …

redirect private routes if user logged in

---

src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js

Put user-name and user email in the local storage.
https://stackoverflow.com/questions/2010892/how-to-store-objects-in-html5-localstorage-sessionstorage
closes#101
Save the username and the email into local storage.

Put username and useremail in local storage

---

package-lock.json
package.json
src/App.js
src/Pages/Search/SearchForm.js
src/Pages/Search/SearchResult.js
src/components/Filter/Filter.js

Search result page renders information entered in the input field on Search form. Filtering buttons were added on the page, and they do filter by cuisine inside the search result
https://mui.com/
closes #75 
Each card with a recipe is retrieved from database.
Filter buttons will filter recipes.
When clicked on the card the user should be directed to an individual Recipe page.
| ✓ | :link: Update dependencies |

Functional search result page with filter

---

src/App.js
src/components/Footer/FooterPublic.js

A link to Spoonacular API was added to Footer.
The Footer now sticks to the bottom.
https://mui.com/material-ui/react-link/
Linking #63  #79 
Refactor the footer to include the credits to spoonacular recipes as per their API with their icon.

Footer public. Added a link to spoonacular. Bug fix

---

src/App.js
src/components/Footer/FooterPrivate.js
src/components/Footer/FooterPublic.js

A link to Spoonacular API was added to the footer.
https://mui.com/material-ui/react-link/
closes #63 #79 
Refactor the footer to include the credits to spoonacular recipes as per their API with their icon.

Footer private. Added link to spoonacular

---

src/App.js

Get the current time,
Check the last login time,
Compare the current time and last login time.
https://stackoverflow.com/questions/45561610/how-can-i-remove-local-storage-after-one-hour 
Check the answer from Nandu
closes #110 
Remove token and user information automatically after 24 hours from local storage.
Take the following steps to not wait 24 hours for testing;
- In the app js file, find the function named removeLocalStorageData,
- Change this method `hours * 60 * 60 * 1000` to `hours * 60 * 1000`, …

remove token and user information

---

src/App.js
src/Pages/Search/SearchForm.js
src/Pages/Search/SearchResult.js
src/components/Filter/Filter.js

Now a user can search for recipes by ingredients and intolerances.
Added a placeholder with an input example. Changed the color of the text on the "new recipe search" button, and added a search icon.
https://www.w3schools.com/
https://www.mui.com/
closes #72 
when clicked on cancel button return to Dashboard page,
when clicked on search button go to Search Result page,
search is filtered by input field and intolerances checkbox

Search form. Intolerances, placeholder, changed design of a new recipe search button

---

src/Pages/Profile/Profile.js
src/Pages/SignUp/SignUp.js

Show Name, Email, and ability to change password.
https://github.com/mui/material-ui/blob/v5.10.14/docs/data/material/getting-started/templates/sign-in/SignIn.js
closes  #64 
It should show the Name, Email, and ability to change the password.
- Click the Edit Account
- Click the Save
- Click change password
- Enter the old password after the new password and Confirm the password. And then save it.

Create a myprofile page

---

src/App.js
src/Pages/NotFound/NotFound.js

I created a 404 not-found page
closes #38 
The page contains a text and a link that return you back to a home page.

create not-found page

---

src/Pages/Landing/Landing.js
src/components/Layout/LayoutPublic.js

Added CSS to remove empty spaces on the sides
!!! This was missed when solving a merge conflict before. We needed to add it.

remove padding on the sides

---

src/Pages/Profile/Profile.js
src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js

Display error message when server responds with 500 status
Remove console logs from axios calls
closes #132 
When server is down and responds with 500 error, display an error message to user
Remove console logs from axios calls
| ✓ | :bug: Bug fix              |
Make sure that server back end is NOT running
- Try to login, or sign up
- You should see the server error message displayed

Fix server down error handling dev

---

src/Pages/Dashboard/Dashboard.css
src/Pages/Search/SearchResult.js
src/components/Filter/Filter.js
src/components/Layout/LayoutPrivate.js

Fixed the background, added user-friendly message when error occurred
| ✓ | :bug: Bug fix              |

fixed the background, added user-friendly message when error occurred

---

src/Pages/Dashboard/Dashboard.css
src/Pages/Favorite/Favorite.js
src/Pages/Recipe/Recipe.css
src/Pages/Recipe/Recipe.js
src/Pages/Search/SearchResult.js
src/components/Navbar/NavBar.js

Fixed all global CSS tags to CSS classes
Added pagination to Favorite page
Pagination on the Favorite page
No global styling
|    ✓| :bug: Bug fix              |

Fix recipe page style div

---

src/components/Footer/FooterPublic.js

Added some more changes to public footer

Footer public footer dev

---

src/Pages/Profile/Profile.css
src/Pages/Profile/Profile.js

Center the profile page
Change the font-size(bold)
Add the Card
Center the profile page
Make the name and email bold
Add the card

fix the profile page

---

src/Pages/Dashboard/Dashboard.css
src/Pages/Dashboard/Dashboard.js
src/Pages/Recipe/Recipe.js

Dashboard carousel fixed 
The single recipe page displays cuisine info
Carousel shows 3 and 3 cards, 
Recipe page displays cuisine type

Dashboard carousel fixed /Single recipe page displays cuisine info

---

README.md

Readme update dev

---

src/Pages/Search/SearchForm.js
src/Pages/Search/SearchResult.js
src/components/Filter/Filter.js
src/components/Navbar/NavBar.js

Fixed the issues mentioned in Acceptance criteria.
closes #153 
Need to remove white spaces in front and back of the search term before sending to the API
Need to reset the filterTerm selected in the searchResults page
Need to add handleLogout() onclick of logout from the navbar
|✓| :bug: Bug fix              |

Fix bug search results filter dev

---

src/App.css
src/App.js
src/Pages/Dashboard/Dashboard.css
src/Pages/Dashboard/Dashboard.js
src/Pages/Favorite/Favorite.css
src/Pages/Favorite/Favorite.js
src/Pages/Profile/Profile.js
src/Pages/Recipe/Recipe.css
src/Pages/Recipe/Recipe.js
src/Pages/Search/SearchResult.js

Fixed responsiveness of Search results, favorite, dashboard, and single recipe pages. 
Profile page password error message

Fix profile search result pages dev

---

src/App.js
src/Pages/Search/SearchResult.js
src/components/Layout/LayoutPublic.js

fixed an error when searching by ingredients with intolerances

fixed an error with breakpoints

---

src/Pages/Profile/Profile.js

When the user changes the password, the success message appears as an alert
After password change, a success message should appear as an alert.
|  ✓   | :hammer: Refactoring       |
- Go to "My Profile" page
- Click "Change Password"
- Enter your current password, a new password and confirm new password
- Click "Save"
- An alert with a success message should appear at the top
- Click "Ok" to go back to profile page

password changed message is an alert now

---

src/Pages/Landing/Landing.js
src/Pages/SignIn/SignIn.js
src/Pages/SignUp/SignUp.js

fixed responsiveness on larger screen

fixed responsiveness on sign up page
